use mini_project;


# mini project on ecomerce


select * from customers_new;

alter table customers_new
rename  column ï»¿customer_Id to customerid;

select * from prod_cat_info;

select * from transactions_new;  

alter table transactions_new
rename column ï»¿transaction_id to transaction_id;


# first procedure to join the table using join 

select * from customers_new C   
join transactions_new T 
join prod_cat_info P  
on C.customerid =T.cust_id and T.prod_cat_code = P.prod_cat_code and T.prod_subcat_code = P.prod_sub_cat_code;

#Q1 what is the total no of row in each of the 3 tables in the database

select count(*) as total_c from customers_new;
select count(*) as total_P from prod_cat_info;
select count(*) as total_t from transactions_new;

# Q2 what is the tota number of transaction that have a return

select count(transaction_id) as transaction_return from transactions_new
where total_amt < 0; 

#Q3 As you would noticed,the dates provided across the dataset are not in a correct format. As first steps,pls convert the data variables into valid date formats
#before proceeding ahead.

select 
     MIN(tran_date) as min_order_date,
     MAX(tran_date) as max_delivery_date,
	 DATEDIFF(MAX(tran_date), MIN(tran_date)) AS total_days,
     timestampdiff(MONTH, MIN(tran_date), MAX(tran_date)) as total_months,
     timestampdiff(YEAR, MIN(tran_date),MAX(tran_date)) as total_years
FROM transactions_new;
     
     #Q4 which product category does the sub-categoru "DIY" belongs to?

 select * from prod_cat_info where prod_subcat = "DIY";
 
     
     #DA Q1. Which channel is most frequently used for transaction?
     
     select S.Store_type from
     (select count(distinct(transaction_id)) as Total_count,Store_type from transactions_new
     group by Store_type
     order by Total_count desc
     limit 1 ) S;
     
     
# DA Q2 what is the count of male and female customer in the database
select count(distinct(customerid)),Gender from customers_new
where Gender in ("M","F")
group by Gender;

# 3.From which city do we have the maximum number of customers and how many?

select city_code, count(distinct (customerid)) as No_of_Customers from customers_new
group by city_code 
order by No_of_Customers desc 
limit 1;



select * from transactions_new;

#Time analysis 

SET SQL_SAFE_UPDATES = 0; 
desc transactions_new;
desc customers_new;

update transactions_new
set tran_date = STR_TO_DATE(tran_date, '%d-%m-%Y')
where tran_date is not null;

alter table transactions_new
change column tran_date tran_date  date not null;

update customers_new
set DOB = STR_TO_DATE(DOB, '%d-%m-%Y')
where DOB is not null;

alter table customers
change column DOB DOB  date not null;





 
 
 
 # DA 4.how many sub-categoreies are there under the books category
 select count(*) from prod_cat_info where prod_cat="Books";
select prod_cat, count(prod_subcat) as No_of_Subcategories 
from prod_cat_info where prod_cat  = 'Books' group by prod_cat;
 

 

 
 # DA:5 What is the Maximum quantity of products ever ordered
 
 select max(Qty) from transactions_new where Qty < 0
 group by max(Qty)
 order by max(QTY) desc;



#DA:8 What is the combined revenue earned from "Electronics" &"Clothing" categories from "Flagship stores"?

select * from transactions_new T 
inner join prod_cat_info P on
T.prod_subcat_code = P.prod_sub_cat_code and
T.prod_cat_code = P.prod_cat_code
having P.prod_cat in ('Electronics','Clothing') and T.Store_type = 'Flagship stores';
 
 
 
 
 #DA11 For all customer aged between 25 and 35 years find what is the net total revenue generated by these consumenr inlast 30 days of transaction from max transcation date available in the date?
 
 /*select TOP 30(tran_date) from transactions_new 
 group by tran_date
 order by tran_date desc limit 30
 
 with ABC as 
(select TOP 30 (tran_date), sum(total_amt) as Total_amount 
from customers_new as C
inner join transaction_new as T
on T.cust_id = C.customerid
where datediff(year,DOB,getdate()) between 25 and 35
group by tran_date
order by tran_date desc)
select sum(Total_amount) as Final_revenue from ABC*/

with ABC as
(select C.customerid, year(curdate())- date_format(str_to_date(DOB,'%d-%m-%Y'),%Y) as Age,T.tran_date,T.total_amt from customers_new C
inner join transaction_new T
on C.customerid = T.cust_id
order by T.tran_date desc)
select customerid,tran_date,Age,sum(total_amt) as Total_sum from abc
group by customerid,tran_date,Age
having Age between 25 and 35
order by Total_sum desc,tran_date desc


 

 
 
 

